(()=>{
const API='https://qfhemprjxezfbrcgdcpg.supabase.co/functions/v1/nutrition-app';
const labels={breakfast:'Завтрак',lunch:'Обед',dinner:'Ужин',snack:'Перекус'},$=id=>document.getElementById(id);
let current=today(),meal='lunch',selected=null,timer=null,key=localStorage.getItem('nutrition_access_key')||'',dayData=null,quickCache=null,addBase=null,editBase=null,editItem=null,statsDays=7,currentView='day';
function today(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Moscow',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
function fmt(s){return new Intl.DateTimeFormat('ru-RU',{timeZone:'Europe/Moscow',day:'numeric',month:'long'}).format(new Date(s+'T12:00:00+03:00'))}
function shortDate(s){return new Intl.DateTimeFormat('ru-RU',{day:'numeric',month:'short'}).format(new Date(s+'T12:00:00+03:00')).replace('.','')}
function n(v){return Number(v||0)}function r(v){return Math.round(v*10)/10}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function nullable(id){const v=$(id).value.trim();return v===''?null:Number(v)}
async function api(q,opt={}){const h=new Headers(opt.headers||{});h.set('x-nutrition-key',key);if(opt.body)h.set('content-type','application/json');let res;try{res=await fetch(API+q,{...opt,headers:h})}catch{throw new Error('Нет связи с API')}let data={};try{data=await res.json()}catch{}if(res.status===401)throw new Error('Неверный код доступа');if(!res.ok)throw new Error(data.error||`Ошибка сервера (${res.status})`);return data}
function grad(p){if(p>100)return'linear-gradient(90deg,#fb923c,#ef4444)';if(p>=90)return'linear-gradient(90deg,#22c55e 0%,#facc15 70%,#fb923c 100%)';if(p>=70)return'linear-gradient(90deg,#22c55e 0%,#a3e635 55%,#facc15 100%)';return'linear-gradient(90deg,#38bdf8,#22c55e)'}
function macro(v,g,a,b,c){$(a).textContent=r(v)+' г';if(g!=null&&Number(g)>0){const p=v/Number(g)*100;$(b).textContent=r(v)+' / '+r(Number(g))+' г · '+Math.round(p)+'%';$(c).style.width=Math.min(100,p)+'%';$(c).style.background=p>100?'#ef4444':p>=90?'#facc15':'#4db7ff'}else{$(b).textContent='цель не задана';$(c).style.width='0'}}
async function load(){ $('dateLabel').textContent=fmt(current);$('screenTitle').textContent=current===today()?'Сегодня':'День';try{const d=await api('?api=day&date='+encodeURIComponent(current));dayData=d;$('gate').classList.add('hidden');render(d);if(currentView==='stats')loadStats()}catch(e){$('gate').classList.remove('hidden');$('gateError').textContent=e.message==='Неверный код доступа'?e.message:'Не удалось загрузить дневник: '+e.message}}
function render(d){const rows=d.meals||[],g=d.target||{},target=Number(g.calorie_intake_target||2000),e=rows.reduce((a,x)=>a+n(x.calories),0),p=rows.reduce((a,x)=>a+n(x.protein_g),0),f=rows.reduce((a,x)=>a+n(x.fat_g),0),c=rows.reduce((a,x)=>a+n(x.carbs_g),0),pct=target?e/target*100:0;$('eaten').textContent=Math.round(e);$('target').textContent=Math.round(target);$('remaining').textContent=e<=target?'Осталось '+Math.round(target-e)+' ккал':'Сверх цели '+Math.round(e-target)+' ккал';$('calBar').style.width=Math.min(100,pct)+'%';$('calBar').style.background=grad(pct);macro(p,g.protein_target_g,'protein','proteinGoal','proteinBar');macro(f,g.fat_target_g,'fat','fatGoal','fatBar');macro(c,g.carbs_target_g,'carbs','carbsGoal','carbsBar');const root=$('meals');root.innerHTML='';['breakfast','lunch','dinner','snack'].forEach(type=>{const arr=rows.filter(x=>x.meal_type===type),sum=arr.reduce((a,x)=>a+n(x.calories),0),sec=document.createElement('div');sec.className='section';const body=arr.length?arr.map(x=>'<button class="item" data-edit="'+x.id+'"><div class="item-main"><div class="item-name">'+esc(x.description)+'</div><div class="item-sub">'+(x.grams?r(n(x.grams))+' г · ':'')+'Б '+(x.protein_g==null?'—':r(n(x.protein_g)))+' · Ж '+(x.fat_g==null?'—':r(n(x.fat_g)))+' · У '+(x.carbs_g==null?'—':r(n(x.carbs_g)))+'</div></div><div class="item-kcal">'+Math.round(n(x.calories))+'</div><span class="item-chevron">›</span></button>').join(''):'<div class="empty">Пока пусто</div>';sec.innerHTML='<div class="section-head"><h2>'+labels[type]+'</h2><div class="section-actions"><span class="section-sum">'+Math.round(sum)+' ккал</span><button class="plus-btn" data-add="'+type+'" aria-label="Добавить">+</button></div></div><div class="card">'+body+'</div>';root.appendChild(sec)});document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>openAdd(b.dataset.add));document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{const x=rows.find(v=>v.id===b.dataset.edit);if(x)openEdit(x)})}
function shift(k){const d=new Date(current+'T12:00:00+03:00');d.setUTCDate(d.getUTCDate()+k);current=d.toISOString().slice(0,10);load()}
function baseFrom(x,gramsKey='grams',kcalKey='calories',pKey='protein_g',fKey='fat_g',cKey='carbs_g'){const grams=Number(x[gramsKey]);if(!Number.isFinite(grams)||grams<=0)return null;return{grams,kcal:n(x[kcalKey]),p:x[pKey]==null?null:n(x[pKey]),f:x[fKey]==null?null:n(x[fKey]),c:x[cKey]==null?null:n(x[cKey])}}
function scale(base,grams,ids,hintId){if(!base||!Number.isFinite(grams)||grams<=0)return;const k=grams/base.grams;$(ids.kcal).value=r(base.kcal*k);$(ids.p).value=base.p==null?'':r(base.p*k);$(ids.f).value=base.f==null?'':r(base.f*k);$(ids.c).value=base.c==null?'':r(base.c*k);$(hintId).textContent=`Пересчитано из базовой порции ${r(base.grams)} г`}
function clearAdd(){selected=null;addBase=null;['foodQuery','kcalInput','gramsInput','proteinInput','fatInput','carbsInput'].forEach(id=>$(id).value='');$('suggestions').innerHTML='';$('suggestions').classList.remove('open');$('addError').textContent='';$('portionHint').textContent=''}
async function openAdd(type){meal=type;clearAdd();$('sectionChip').textContent=labels[type];$('addSheet').classList.add('open');renderQuick();if(!quickCache){try{quickCache=await api('?api=quick');renderQuick()}catch{}}setTimeout(()=>$('foodQuery').focus(),80)}
function closeAdd(){$('addSheet').classList.remove('open');$('suggestions').classList.remove('open')}
function renderQuick(){const draw=(id,rows,frequent=false)=>{$(id).innerHTML=rows?.length?rows.map((x,i)=>'<button class="quick-food" data-q="'+id+'-'+i+'"><b>'+esc(x.description)+'</b><span>'+Math.round(n(x.calories))+' ккал'+(frequent?' · '+x.count+'×':'')+'</span></button>').join(''):'<span class="muted" style="font-size:11px">Появятся после нескольких записей</span>';$(id).querySelectorAll('[data-q]').forEach((b,i)=>b.onclick=()=>chooseQuick(rows[i]))};draw('recentFoods',quickCache?.recent||[]);draw('frequentFoods',quickCache?.frequent||[],true)}
function chooseQuick(x){selected=x.catalog_id?{id:x.catalog_id}:null;$('foodQuery').value=x.description;$('kcalInput').value=x.calories??'';$('gramsInput').value=x.grams??'';$('proteinInput').value=x.protein_g??'';$('fatInput').value=x.fat_g??'';$('carbsInput').value=x.carbs_g??'';addBase=baseFrom(x);$('portionHint').textContent=addBase?`Базовая порция ${r(addBase.grams)} г — меняйте граммы, КБЖУ пересчитаются`:''}
async function search(){const q=$('foodQuery').value.trim();if(q.length<2){$('suggestions').classList.remove('open');return}try{const rows=await api('?api=search&q='+encodeURIComponent(q)),box=$('suggestions');if(!rows.length){box.classList.remove('open');box.innerHTML='';return}box.innerHTML=rows.map((x,i)=>'<button class="suggestion" data-i="'+i+'"><div><div class="s-name">'+esc(x.canonical_name)+'</div><div class="s-brand">'+esc(x.brand||'')+'</div></div><div class="s-kcal">'+Math.round(n(x.calories_kcal))+' ккал</div></button>').join('');box.classList.add('open');box.querySelectorAll('[data-i]').forEach((b,i)=>b.onclick=()=>choose(rows[i]))}catch(e){$('addError').textContent=e.message}}
function choose(x){selected=x;$('foodQuery').value=x.canonical_name+(x.brand?' — '+x.brand:'');$('kcalInput').value=x.calories_kcal??'';$('gramsInput').value=x.serving_weight_g??'';$('proteinInput').value=x.protein_g??'';$('fatInput').value=x.fat_g??'';$('carbsInput').value=x.carbs_g??'';addBase=baseFrom(x,'serving_weight_g','calories_kcal');$('portionHint').textContent=addBase?`Стандартная порция ${r(addBase.grams)} г — измените вес для пересчёта`:x.serving_volume_ml?`Стандартный объём ${r(n(x.serving_volume_ml))} мл`:'';$('suggestions').classList.remove('open')}
async function saveFood(){const desc=$('foodQuery').value.trim(),kcal=Number($('kcalInput').value);if(!desc||!Number.isFinite(kcal)){$('addError').textContent='Выберите продукт или заполните название и калории';return}try{$('saveAdd').disabled=true;await api('?api=add',{method:'POST',body:JSON.stringify({date:current,meal_type:meal,catalog_id:selected?selected.id:null,description:desc,grams:nullable('gramsInput'),calories:kcal,protein_g:nullable('proteinInput'),fat_g:nullable('fatInput'),carbs_g:nullable('carbsInput')})});quickCache=null;closeAdd();await load()}catch(e){$('addError').textContent=e.message}finally{$('saveAdd').disabled=false}}
function openEdit(x){editItem=x;editBase=baseFrom(x);$('editMeal').value=x.meal_type;$('editName').value=x.description;$('editKcal').value=x.calories??'';$('editGrams').value=x.grams??'';$('editProtein').value=x.protein_g??'';$('editFat').value=x.fat_g??'';$('editCarbs').value=x.carbs_g??'';$('editError').textContent='';$('editPortionHint').textContent=editBase?`Исходная порция ${r(editBase.grams)} г — изменение веса пересчитает КБЖУ`:'';$('editSheet').classList.add('open')}
function closeEdit(){$('editSheet').classList.remove('open');editItem=null;editBase=null}
async function saveEdit(){if(!editItem)return;const kcal=Number($('editKcal').value),description=$('editName').value.trim();if(!description||!Number.isFinite(kcal)){$('editError').textContent='Нужны название и калории';return}try{$('saveEdit').disabled=true;await api('?api=edit',{method:'POST',body:JSON.stringify({id:editItem.id,meal_type:$('editMeal').value,description,grams:nullable('editGrams'),calories:kcal,protein_g:nullable('editProtein'),fat_g:nullable('editFat'),carbs_g:nullable('editCarbs')})});quickCache=null;closeEdit();await load()}catch(e){$('editError').textContent=e.message}finally{$('saveEdit').disabled=false}}
async function deleteEntry(){if(!editItem||!confirm(`Удалить «${editItem.description}» из дневника?`))return;try{$('deleteEntry').disabled=true;await api('?api=delete',{method:'POST',body:JSON.stringify({id:editItem.id})});quickCache=null;closeEdit();await load()}catch(e){$('editError').textContent=e.message}finally{$('deleteEntry').disabled=false}}
async function openGoals(){try{const d=dayData&&dayData.date===current?dayData:await api('?api=day&date='+encodeURIComponent(current)),g=d.target||{};$('goalKcal').value=g.calorie_intake_target??2000;$('goalProtein').value=g.protein_target_g??'';$('goalFat').value=g.fat_target_g??'';$('goalCarbs').value=g.carbs_target_g??'';$('settingsError').textContent='';$('settingsSheet').classList.add('open')}catch(e){alert(e.message)}}
function closeGoals(){$('settingsSheet').classList.remove('open')}
async function saveGoals(){const kcal=Number($('goalKcal').value);if(!Number.isFinite(kcal)||kcal<=0){$('settingsError').textContent='Укажите цель по калориям';return}try{$('saveSettings').disabled=true;await api('?api=goals',{method:'POST',body:JSON.stringify({date:current,calorie_intake_target:kcal,protein_target_g:nullable('goalProtein'),fat_target_g:nullable('goalFat'),carbs_target_g:nullable('goalCarbs')})});closeGoals();await load()}catch(e){$('settingsError').textContent=e.message}finally{$('saveSettings').disabled=false}}
function switchView(v){currentView=v;$('dayView').classList.toggle('active',v==='day');$('statsView').classList.toggle('active',v==='stats');$('dayTab').classList.toggle('active',v==='day');$('statsTab').classList.toggle('active',v==='stats');if(v==='stats')loadStats()}
async function loadStats(){try{const d=await api('?api=stats&days='+statsDays+'&end='+encodeURIComponent(current));renderStats(d)}catch(e){$('statsSummary').innerHTML='<div class="error">'+esc(e.message)+'</div>'}}
function renderStats(d){const daily=d.daily||[],logged=daily.filter(x=>x.entries>0),den=logged.length||1,sum=logged.reduce((a,x)=>a+n(x.calories),0),avg=sum/den,hit=logged.filter(x=>x.target&&x.calories>=x.target*.9&&x.calories<=x.target*1.05).length;$('statsPeriod').textContent=daily.length?(shortDate(daily[0].date)+' — '+shortDate(daily[daily.length-1].date)):'';$('statsSummary').innerHTML='<div class="stat-box"><span>Среднее за день</span><b>'+Math.round(avg)+' ккал</b></div><div class="stat-box"><span>Дней с записями</span><b>'+logged.length+' / '+daily.length+'</b></div><div class="stat-box"><span>В диапазоне цели</span><b>'+hit+' дн.</b></div><div class="stat-box"><span>Всего записей</span><b>'+logged.reduce((a,x)=>a+n(x.entries),0)+'</b></div>';
$('dailyChart').innerHTML=daily.map((x,i)=>{const pct=x.target?x.calories/x.target*100:0,h=Math.min(100,pct/1.2),show=daily.length<=10||i%5===0||i===daily.length-1;return'<div class="day-col" title="'+shortDate(x.date)+': '+Math.round(x.calories)+' ккал"><div class="day-bar-wrap"><div class="day-bar '+(pct>100?'over':'')+'" style="height:'+h+'%"></div></div><div class="day-label">'+(show?shortDate(x.date).split(' ')[0]:'')+'</div></div>'}).join('');
const mt=d.meal_totals||{},total=Object.values(mt).reduce((a,v)=>a+n(v),0)||1;$('mealDistribution').innerHTML=['breakfast','lunch','dinner','snack'].map(t=>{const v=n(mt[t]),p=v/total*100;return'<div class="dist-row"><div class="dist-meta"><span>'+labels[t]+'</span><span>'+Math.round(v)+' ккал · '+Math.round(p)+'%</span></div><div class="dist-track"><div class="dist-fill" style="width:'+p+'%"></div></div></div>'}).join('');
const ap=logged.reduce((a,x)=>a+n(x.protein_g),0)/den,af=logged.reduce((a,x)=>a+n(x.fat_g),0)/den,ac=logged.reduce((a,x)=>a+n(x.carbs_g),0)/den;$('macroStats').innerHTML='<div class="stat-macro"><b>'+r(ap)+' г</b><span>Белки / день</span></div><div class="stat-macro"><b>'+r(af)+' г</b><span>Жиры / день</span></div><div class="stat-macro"><b>'+r(ac)+' г</b><span>Углеводы / день</span></div>'}
async function unlock(){key=$('accessInput').value.trim();$('gateError').textContent='';try{await api('?api=ping');localStorage.setItem('nutrition_access_key',key);$('gate').classList.add('hidden');await load()}catch(e){$('gateError').textContent=e.message}}
function bind(){$('prev').onclick=()=>shift(-1);$('next').onclick=()=>shift(1);$('settingsBtn').onclick=openGoals;$('cancelAdd').onclick=closeAdd;$('saveAdd').onclick=saveFood;$('cancelEdit').onclick=closeEdit;$('saveEdit').onclick=saveEdit;$('deleteEntry').onclick=deleteEntry;$('cancelSettings').onclick=closeGoals;$('saveSettings').onclick=saveGoals;$('unlockBtn').onclick=unlock;$('dayTab').onclick=()=>switchView('day');$('statsTab').onclick=()=>switchView('stats');$('accessInput').addEventListener('keydown',e=>{if(e.key==='Enter')unlock()});$('foodQuery').addEventListener('input',()=>{selected=null;addBase=null;$('portionHint').textContent='';clearTimeout(timer);timer=setTimeout(search,180)});$('gramsInput').addEventListener('input',()=>scale(addBase,Number($('gramsInput').value),{kcal:'kcalInput',p:'proteinInput',f:'fatInput',c:'carbsInput'},'portionHint'));$('editGrams').addEventListener('input',()=>scale(editBase,Number($('editGrams').value),{kcal:'editKcal',p:'editProtein',f:'editFat',c:'editCarbs'},'editPortionHint'));document.querySelectorAll('[data-days]').forEach(b=>b.onclick=()=>{statsDays=Number(b.dataset.days);document.querySelectorAll('[data-days]').forEach(x=>x.classList.toggle('active',x===b));loadStats()});$('addSheet').onclick=e=>{if(e.target===$('addSheet'))closeAdd()};$('editSheet').onclick=e=>{if(e.target===$('editSheet'))closeEdit()};$('settingsSheet').onclick=e=>{if(e.target===$('settingsSheet'))closeGoals()};window.addEventListener('online',()=>{$('offline').style.display='none';if(key)load()});window.addEventListener('offline',()=>{$('offline').style.display='block'});if(!navigator.onLine)$('offline').style.display='block'}
window.addEventListener('error',e=>{const x=$('gateError');if(x&&!$('gate').classList.contains('hidden'))x.textContent='Ошибка интерфейса: '+e.message});bind();if(key)load();else $('gate').classList.remove('hidden');
})();